/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as test from "./test";
export type { test };
export type { Desvot } from "./Desvot";
export type { RandomNumberConsumerV2 } from "./RandomNumberConsumerV2";
