/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as test from "./test";
export { Desvot__factory } from "./Desvot__factory";
export { RandomNumberConsumerV2__factory } from "./RandomNumberConsumerV2__factory";
